name: project_tugas_akhir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  build_runner: ^2.3.3
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  dwds: ^16.0.1
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  flutter:
    sdk: flutter
  flutter_cors: ^1.3.2
  font_awesome_flutter: ^10.4.0
  form_field_validator: ^1.1.0
  get: 4.6.5
  hexcolor: ^3.0.1
  iconly: ^1.0.1
  icons_plus: ^4.0.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  responsive_framework: ^0.2.0
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Thin.ttf
          weight: 100
        - asset: fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter-Black.ttf
          weight: 900
  uses-material-design: true
